const ITEM_ICONS: Record<string, string> = {
  "milk tea": "🧋",
  local: "🧋",
  chocolate: "🍫",
  "black coffee": "☕",
  "milk coffee": "☕",
  "cold coffee": "🥤",
  "iced coffee": "🥤",
  "liquor tea": "🫖",
  classic: "🫖",
  "lemon tea": "🍋",
  "adrak tea": "🫚",
  "orange tea": "🍊",
  "lemon ice tea": "🧊",
  "ice tea": "🧊",
  "masala cold drinks": "🥤",
  "cold drinks": "🥤",
  "green tea": "🍵",
  "masala tea": "🫖",
  "black tea": "🫖",
  "hot chocolate": "☕",
  "french fries": "🍟",
  "masala egg": "🥚",
  "masala veg": "🍜",
  "chicken cheese": "🥪",
  "double cheese": "🧀",
  "subway sandwich": "🥖",
  "veg sandwich": "🥪",
  "cheese sandwich": "🥪",
  "chicken sandwich": "🥪",
  "veg burger": "🍔",
  "cheese burger": "🍔",
  "chicken burger": "🍔",
  "chocolate cake": "🍰",
  brownie: "🍫",
  muffin: "🧁",
  cupcake: "🧁",
  "ice cream": "🍨",
  milkshake: "🥤",
  smoothie: "🥤",
  "fresh juice": "🧃",
  lemonade: "🍋",
  pasta: "🍝",
  pizza: "🍕",
  noodles: "🍜",
  "bread toast": "🍞",
  "dim toast": "🍳",
  "butter toast": "🧈",
  "pao pao": "🥯",
  "tehelka omelette": "🍳",
  omelette: "🍳",
  "poached eggs": "🥚",
  "packaging fee": "📦",
  packaging: "📦",
  momos: "🥟",
  samosa: "🥟",
  cookie: "🍪",
  cookies: "🍪",
  biscuit: "🍪",
  tea: "🧋",
  coffee: "☕",
  cappuccino: "☕",
  latte: "☕",
  espresso: "☕",
  mocha: "☕",
  sandwich: "🥪",
  burger: "🍔",
  fries: "🍟",
  cake: "🍰",
  pastry: "🥐",
  croissant: "🥐",
  donut: "🍩",
  doughnut: "🍩",
  juice: "🧃",
  soda: "🥤",
  coke: "🥤",
  cola: "🥤",
  water: "💧",
  wrap: "🌯",
  roll: "🌯",
  maggi: "🍜",
  paneer: "🧀",
  cheese: "🧀",
  egg: "🥚",
  salad: "🥗",
  soup: "🥣",
  rice: "🍚",
  biryani: "🍛",
  toast: "🍞",
  bread: "🍞",
};

export function getItemEmoji(itemName: string) {
  const key = itemName.toLowerCase();
  return (
    Object.entries(ITEM_ICONS).find(([name]) => key.includes(name))?.[1] ?? "✨"
  );
}
